### PR TITLE
[prepInputs] add caching for checksums

### PR DESCRIPTION
**Pull request by ygc2l**

### CODE REVIEW

**Comment by ygc2l** [comment]
This would still re-run checksums the next call of prepInputs if any of the files listed in CHECKSUMS.txt was downloaded (or extracted) and thus is now present in the list. This happened to me many times.

**Comment by ygc2l** [comment]
Now, I think you got a point with file.info(), it should run only on the files in CHECKSUMS.txt. Or maybe it should only check if CHECKSUMS.txt has changed?

**Comment by ygc2l** [comment]
Ok. I also figured out that 

```
  capturedOutput <- capture.output(
    tmp <- Cache(file.info, asPath(dir(dataPath, full.names = TRUE)), userTags = cacheTags),
    type = "message"
  )
```
does not work on RStudio!

**Comment by eliotmcintire** [comment]
>  Now, I think you got a point with file.info(), it should run only on the files in CHECKSUMS.txt. Or maybe it should only check if CHECKSUMS.txt has changed?

I think in this case, it may only need to check the `file.info` of the `targetFile`, no? Also, if that is the case, then we don't need a `Cache` around the `file.info`, otherwise, it is actually running `digest` on the file content, which is what we are trying to avoid, if we can.

**Comment by eliotmcintire** [comment]
> Ok. I also figured out that
>     `capturedOutput <- capture.output(`
>     `tmp <- Cache(file.info, asPath(dir(dataPath, full.names = TRUE)), userTags = cacheTags),`
>     `type = "message"`
>   `)`
> does not work on RStudio!

A) More specific
B) You may need to pass cacheRepo ...

**Comment by ygc2l** [comment]
I am not sure file.info on `targetFile` is always reliable which is probably one of the reasons why people are using checksums in the first place.

Digesting the file content should run once unless CHECKSUMS.txt changed, so Cache(digest,...) does the trick.

About `capture.output`, see my edit, our messages crossed. In summary it's related with Rmd files.

I stumbled across `utils::changedFiles`, did you know about it?

**Comment by eliotmcintire** [comment]
I had seed `utils::changedFiles`, but it didn't seem to be better than what we were using.

You are correct about `file.info` not being "reliable". Presumably, that check should be part of the `quick` argument, i.e., the user gets to decide. 

>Digesting the file content should run once unless CHECKSUMS.txt changed, so Cache(digest,...) does the trick.

Yes. 

> About capture.output, see my edit, our messages crossed. In summary it's related with Rmd files.

Not sure what to say about this.

The objective is to be able to do the correct (digest), but fast (only the files necessary) "deep check", unless `quick` is specified as `TRUE`. Then use the "less correct", but much faster `file.info`.

I approved your `Cache(digest...)` suggestion, pulled it in, but as I said, I would rather it in the `SpaDES.core::checksums` down the road...

**Pull request merged**
