### PR TITLE
gaussMap alternative models

### PR DESCRIPTION
**Pull request by ianmseddy**
Added potential alternatives to exponential model used in gaussMap function

### CODE REVIEW

**Comment by achubaty** [comment]
@ianmseddy can you please resubmit this one to the development branch?

**Comment by achubaty** [comment]
https://github.com/blog/2224-change-the-base-branch-of-a-pull-request

**Comment by achubaty** [comment]
hopefully it lets you do this even though the changes were merged (then reverted). you may need to make an additional change (update date in DESCRIPTION).

**Comment by ianmseddy** [comment]
It doesn't give me the option when I try to edit it. I think because it was already merged, whereas the example it is still open.

**Comment by ianmseddy** [comment]
[https://stackoverflow.com/questions/12674304/github-reopening-a-merged-pull-request](url)

apparently I cant

**Comment by achubaty** [comment]
Ok then, I guess you'll have to make a new PR. I was hoping GitHub would make this easier...

**Comment by achubaty** [comment]
since it was just 4 commits, I cherrypicked them, added some changes of my own and squashed into a single commit on development

**Pull request merged**
