### PR TITLE
[downloadInputs] Fix checksums check

### PR DESCRIPTION
**Pull request by ygc2l**

### CODE REVIEW

**Comment by eliotmcintire** [comment]
We need to provide the option of doing a quickCheck ... I don't think it should be removed.

**Comment by ygc2l** [comment]
Sure. Would you mind modifying SpaDES.core::checksums() so that it does not drop the info about filesize. That way we can allow for .quickCheck.

**Comment by eliotmcintire** [comment]
I don't think the development version of SpaDES.core::checksums does drop
filesize

**Comment by eliotmcintire** [comment]
I believe you may be referring to the point which is that many existing
modules *don't have* a file size in their checksums. So, for those modules,
we need to rerun checksums(..., write = TRUE). Then they will get a
filesize column. Then we can run checksums(   , quickCheck = TRUE) and it
will work.

**Comment by ygc2l** [comment]
The data.frame that SpaDES.core::checksums outputs has the following columns: result, expectedFile, actualFile, checksum.x, checksum.y, algorithm.x, algorithm.y while the info about filesize is present in the data/CHECKSUMS.txt file (it has info about file, checksum, filesize and algorithm). That's why I am suspecting that checksums drops the info about the filesize.

**Comment by eliotmcintire** [comment]
You perhaps have an old version of SpaDES.core?  Please get the latest version PredictiveEcology/SpaDES.core . It will be pushed to CRAN this week.

**Comment by ygc2l** [comment]
I tried the development branch of SpaDES.core, freshly downloaded this morning.

**Comment by eliotmcintire** [comment]
The larger issue is as described above, you do not need a filesize column. You need the `results` column. If you did a checksums(quick = TRUE), then it used the filesize column to determine `results`. There is no need to have a filesize column.

**Comment by eliotmcintire** [comment]
If you would like a `filesize` column retained, then you can do a pull request, or I will add it to my list (long)

**Comment by ygc2l** [comment]
As you said, now I am understanding it, there is no need for the filesize to be retained. I will revert some changes to allow for .quickCheck.

**Comment by eliotmcintire** [comment]
Also, note that I changed the argument name from `.quickCheck` to `quick`

**Comment by ygc2l** [comment]
I pushed some updates to address your comments. Should I PR the development branch instead of the prepInputs branch ?

**Comment by eliotmcintire** [comment]
prepInputs branch may be a bit stale. I have pulled `prepInputs` into development. If you are adding experimental features, then make sure the prepInputs branch is updated from development.

**Comment by ygc2l** [comment]
Done. This should be the last PR.

**Pull request merged**
