### PR TITLE
spread2 persistence

### PR DESCRIPTION
**Pull request by CeresBarros**
Added persistence argument to spread2 + tests for this argument

### CODE REVIEW

**Comment by eliotmcintire** [comment]
@CeresBarros 

I think I see at least 2 bugs:

1. SHouldn't the first `if` here be an || instead of & (i.e., or)?
```
if(length(persistProb) == 1 & all(is.na(persistProb[]))) {} else {
        # Extract persistenceProb for the current set of source pixels
        actualPersistProb <- if (length(persistProb) == 1) {
          rep(persistProb, sum(dt$state == "activeSource"))
        } else {
          persistProb[dt[state == "activeSource", initialPixels]]
        }
```
If this is indeed wrong, did tests pass? Look atthe tests:

2. Shouldn't the test set the seed 2x, once before each run:
```
set.seed(5)
  noPersist <- spread2(landscape = landscape, start = start, asRaster = FALSE,
                       spreadProb = 0.23, persistProb = 0, iterations = 10, directions = 8L, plot.it = FALSE)
 set.seed(5) # add this to get the correct comparison
  wPersist <- spread2(landscape = landscape, start = start, asRaster = FALSE,
                      spreadProb = 0.23, persistProb = 0.8, iterations = 10, directions = 8L, plot.it = FALSE)

  expect_true(sum(noPersist$state == "activeSource") < sum(wPersist$state == "activeSource"))

```

**Comment by CeresBarros** [comment]
Bug 1. is not a bug. I t should not be an OR, because I want to make sure that persistProb is of length 1 AND NA (meaning that the default value has not been changed). I just checked this again and it’s doing what I want.

When I run the tests one at a time they don’t seem to fail. Also, if I used RstudioReporter, I also don’t see failures. They appear with the default reporter.

So, I don’t know.

**Comment by eliotmcintire** [comment]
Ok. I think it is  a stylistic thing. I didn't seee that you *didn't* do anything with the `TRUE` option.  But taht is fine.

I would say that all(is.na(spreadProb[])) is VERY slow for a large raster. So, is there a different way you can test for this?

**Comment by CeresBarros** [comment]
I don’t know from the top of my head. Perhaps go for a sum(spreadProb[], na.rm = T) == 0? But it’s not exactly the same.

**Comment by CeresBarros** [comment]
I was trying to avoid having multiple if clauses, because I thought it’d be slower. But I guess once rasters become too big, it’s preferable to have it as you suggest.

**Comment by eliotmcintire** [comment]
A few points about speed:

Primitives are fast. They are always preferred ... So the above 2 ifs and 1
is.null is vastly faster than `any(is.na(persistProb[]))` even for small
rasters

```
is.null
#function (x)  .Primitive("is.null")
is.na
#function (x)  .Primitive("is.na")
`if`
# .Primitive("if")
length
# function (x)  .Primitive("length")
sum
# function (..., na.rm = FALSE)  .Primitive("sum")
 ...
```

**Comment by eliotmcintire** [comment]
A few points about speed:

Primitives are fast. They are always preferred ... So the above 2 ifs and 1
is.null is vastly faster than `any(is.na(persistProb[]))` even for small
rasters

```
is.null
#function (x)  .Primitive("is.null")
is.na
#function (x)  .Primitive("is.na")
`if`
# .Primitive("if")
length
# function (x)  .Primitive("length")
sum
# function (..., na.rm = FALSE)  .Primitive("sum")
 ...
```

**Comment by CeresBarros** [comment]
Good to know!

**Comment by CeresBarros** [comment]
I have now incorporated @eliotmcintire 's suggestions.

**Pull request merged**
