### PR TITLE
new function `neutralLandscapeMap`to replace `gaussMap`

### PR DESCRIPTION
**Pull request by CeresBarros**
`neutralLandscapeMap`, replaces the deprecated `gaussMap` in creating a neutral landscape map using the midpoint displacement algorithm available in `NLMR::nlm_mpd`. It uses a template raster and ensures that the output raster has the same extent and resolution as the template.

### CODE REVIEW

**Comment by CeresBarros** [comment]
@achubaty please review/merge ASAP as this is needed for LandR, SpaDES.core and Biomass_core

**Review by achubaty — APPROVED** [review]
other than the example, are there additional tests? we should make sure that the dimensions are consistently the same.

i'll add some simple ones for now and we can come back to them as needed.

**Comment by CeresBarros** [comment]
thanks @achubaty

**Comment by achubaty** [comment]
thanks @CeresBarros !

**Pull request merged**
